### PR TITLE
code/user interactions

### PR DESCRIPTION
**Pull request by mgstraface**
* Follow & unfollow functions/routes
* Block & unblock functions/routes
* Mute & unmute functions/routes

### CODE REVIEW

**Review by Sebastian-pz — APPROVED** [review]
looks good 👍🏻

**Comment by Sebastian-pz** [comment]
@mgstraface || @MelHellrigl  can merge

**Review by MelHellrigl — APPROVED** [review]
Perfect!

**Comment by Sebastian-pz** [comment]
- [ ] a

**Comment by MelHellrigl** [comment]
> @mgstraface || @MelHellrigl can merge

👍👍👍

**Pull request merged**
